import type { Metadata } from 'next'
import { sahel } from '@/lib/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'فروشگاه',
  description: 'Generated by create next app',
}

export default function RootLayout(props: LayoutProp) {
  const { children } = props

  return (
    <html lang="fa" dir='rtl'>
      <body className={`${sahel.variable} font-sahel`}>
        {children}
      </body>
    </html>
  )
}
